/* Curated IAVE / national exam tracker links */
window.IAVE_EXAMS = [
  {
    id: "fq-2024-1",
    subject: "FQ",
    label: "FQ A — 1.ª fase 2024",
    url: "https://iave.pt/download/exame-final-nacional-de-fisica-e-quimica-a-702-1-a-fase-2024/",
    year: 2024,
    phase: "1.ª fase",
  },
  {
    id: "fq-2024-2",
    subject: "FQ",
    label: "FQ A — 2.ª fase 2024",
    url: "https://iave.pt/download/exame-final-nacional-de-fisica-e-quimica-a-702-2-a-fase-2024/",
    year: 2024,
    phase: "2.ª fase",
  },
  {
    id: "fq-2023-1",
    subject: "FQ",
    label: "FQ A — 1.ª fase 2023",
    url: "https://iave.pt/download/exame-final-nacional-de-fisica-e-quimica-a-702-1-a-fase-2023/",
    year: 2023,
    phase: "1.ª fase",
  },
  {
    id: "fq-2023-2",
    subject: "FQ",
    label: "FQ A — 2.ª fase 2023",
    url: "https://iave.pt/download/exame-final-nacional-de-fisica-e-quimica-a-702-2-a-fase-2023/",
    year: 2023,
    phase: "2.ª fase",
  },
  {
    id: "fq-2022-1",
    subject: "FQ",
    label: "FQ A — 1.ª fase 2022",
    url: "https://iave.pt/download/exame-final-nacional-de-fisica-e-quimica-a-702-1-a-fase-2022/",
    year: 2022,
    phase: "1.ª fase",
  },
  {
    id: "mat-2024-1",
    subject: "MAT",
    label: "Matemática A — 1.ª fase 2024",
    url: "https://iave.pt/download/exame-final-nacional-de-matematica-a-635-1-a-fase-2024/",
    year: 2024,
    phase: "1.ª fase",
  },
  {
    id: "mat-2024-2",
    subject: "MAT",
    label: "Matemática A — 2.ª fase 2024",
    url: "https://iave.pt/download/exame-final-nacional-de-matematica-a-635-2-a-fase-2024/",
    year: 2024,
    phase: "2.ª fase",
  },
  {
    id: "mat-2023-1",
    subject: "MAT",
    label: "Matemática A — 1.ª fase 2023",
    url: "https://iave.pt/download/exame-final-nacional-de-matematica-a-635-1-a-fase-2023/",
    year: 2023,
    phase: "1.ª fase",
  },
  {
    id: "mat-2023-2",
    subject: "MAT",
    label: "Matemática A — 2.ª fase 2023",
    url: "https://iave.pt/download/exame-final-nacional-de-matematica-a-635-2-a-fase-2023/",
    year: 2023,
    phase: "2.ª fase",
  },
  {
    id: "mat-2022-1",
    subject: "MAT",
    label: "Matemática A — 1.ª fase 2022",
    url: "https://iave.pt/download/exame-final-nacional-de-matematica-a-635-1-a-fase-2022/",
    year: 2022,
    phase: "1.ª fase",
  },
  {
    id: "port-2024-1",
    subject: "PORT",
    label: "Português — 1.ª fase 2024",
    url: "https://iave.pt/download/exame-final-nacional-de-portugues-639-1-a-fase-2024/",
    year: 2024,
    phase: "1.ª fase",
  },
  {
    id: "port-2024-2",
    subject: "PORT",
    label: "Português — 2.ª fase 2024",
    url: "https://iave.pt/download/exame-final-nacional-de-portugues-639-2-a-fase-2024/",
    year: 2024,
    phase: "2.ª fase",
  },
  {
    id: "port-2023-1",
    subject: "PORT",
    label: "Português — 1.ª fase 2023",
    url: "https://iave.pt/download/exame-final-nacional-de-portugues-639-1-a-fase-2023/",
    year: 2023,
    phase: "1.ª fase",
  },
  {
    id: "port-2023-2",
    subject: "PORT",
    label: "Português — 2.ª fase 2023",
    url: "https://iave.pt/download/exame-final-nacional-de-portugues-639-2-a-fase-2023/",
    year: 2023,
    phase: "2.ª fase",
  },
  {
    id: "port-2022-1",
    subject: "PORT",
    label: "Português — 1.ª fase 2022",
    url: "https://iave.pt/download/exame-final-nacional-de-portugues-639-1-a-fase-2022/",
    year: 2022,
    phase: "1.ª fase",
  },
  {
    id: "iave-hub",
    subject: "FQ",
    label: "Portal IAVE — Provas e Exames (hub)",
    url: "https://iave.pt/provas-e-exames/",
    year: null,
    phase: "Portal",
  },
];

window.SIMULACRO_SLOTS = [
  { id: "sim1-fq", week: 25, subject: "FQ", label: "Simulacro 1 — FQ A", max: 200 },
  { id: "sim1-mat", week: 25, subject: "MAT", label: "Simulacro 1 — Matemática A", max: 200 },
  { id: "sim1-port", week: 25, subject: "PORT", label: "Simulacro 1 — Português", max: 200 },
  { id: "sim2-fq", week: 27, subject: "FQ", label: "Simulacro 2 — FQ A", max: 200 },
  { id: "sim2-mat", week: 27, subject: "MAT", label: "Simulacro 2 — Matemática A", max: 200 },
  { id: "sim2-port", week: 27, subject: "PORT", label: "Simulacro 2 — Português", max: 200 },
  { id: "simf-fq", week: 30, subject: "FQ", label: "Simulacro final — FQ A", max: 200 },
  { id: "simf-mat", week: 30, subject: "MAT", label: "Simulacro final — Matemática A", max: 200 },
  { id: "simf-port", week: 30, subject: "PORT", label: "Simulacro final — Português", max: 200 },
];
